import "./http2p-test.js";
import "./gateway-http2p-test.js";
import "./http2p-event-source-test.js";
import "./text-event-stream-body-test.js";
import "./coop-create-stop-test.js";
import "./coop-test.js";
import "./coop-many-nodes-test.js";
import "./coop-mdns-test.js";
import "./coop-helia-test.js";
